name: tn
on:
  workflow_dispatch:
  #schedule:
   #  - cron: '*/15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajonly/1
          ref: 'main'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 'run ttx'
        run: |
           node tjs.js
        env:
          JRTTSIGNURL: ${{ secrets.JRTTSIGNURL }}
          JRTTSIGNKEY: ${{ secrets.JRTTSIGNKEY }}
          JRTTFARMURL: ${{ secrets.JRTTFARMURL }}
          JRTTFARMKEY: ${{ secrets.JRTTFARMKEY }}
          JRTTREADURL: ${{ secrets.JRTTREADURL }}
          JRTTREADKEY: ${{ secrets.JRTTREADKEY }}
          XLC: ${{ secrets.XLC }}
          GITHUB: ${{ secrets.GITHUB }}
          EFORK: ${{ secrets.EFORK }}

      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
      - name: npm install
        run: |
              npm install
      - name: 'run qj'
        run: |
           node xlcsecret-All.js
        env:
          QCZJ_GetUserInfoHEADER: ${{ secrets.QCZJ_GetUserInfoHEADER }}
          QCZJ_activityBODY: ${{ secrets.QCZJ_activityBODY }}	
          QCZJ_addCoinBODY: ${{ secrets.QCZJ_addCoinBODY }}
          QCZJ_addCoin2BODY: ${{ secrets.QCZJ_addCoin2BODY }}
          SYNCURL: qczjspeed.js
          XLC: ${{ secrets.XLC }}
          GITHUB: ${{ secrets.GITHUB }}
          EFORK: ${{ secrets.EFORK }} 
  dispatch:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: ' wait'
        run: |
          sleep 15m
          sleep $(($RANDOM%5))
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}

      - name: De Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
