name: y_rpy
on:
  workflow_dispatch:
  schedule:
     - cron: '55 9-23/6, * * *'
  watch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajonly/1
          ref: 'main'
          token: ${{ secrets.PAT }}
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7       
      - name: 'Install requests'
        run: pip install requests
      - name: 'run rdpy'
        run: python3 rd.py
        env:
            XLC: ${{ secrets.XLC }} 


