name: yshaY

on:
  workflow_dispatch:
  schedule:
     - cron: '*/15 * * * *'
  watch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajonly/1
          ref: 'main'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
              npm install
              npm install cron
              npm install request
              npm install md5-node
      - name: 'ysha'
        run: |
          node ysha.js
        env:
           XLC: ${{ secrets.XLC }} 
           Y_TE: ${{ secrets.Y_TE}}
           
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajonly/1
          ref: 'main'
          token: ${{ secrets.PAT }}
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7       
      - name: 'Install requests'
        run: pip install requests
      - name: 'run yhpy'
        run: python3 yh.py
        
        env:
           XLC: ${{ secrets.XLC }}
           Y_TE: ${{ secrets.Y_TE}}

         
      - name: De Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
           
